# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrams', '0006_dictionary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='word',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
